name: Send mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World"

    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.gmail.com
        # Optional port (defaults to 465)
        port: 587
        account: ${{ secrets.ACCOUNT }}
        password: ${{ secrets.MAIL_PASSWORD }}
        sender: boopathy
        from: ${{ secrets.MAIL_ADDRESS }}
        to: nboopathy02@gmail.com
        subject: mail title.
        body: this is my test email
