name: CI/CD Pipeline with Email Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch email credentials from AWS Secrets Manager
      - name: Fetch email credentials
        id: fetch-secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SECRET_NAME: ${{ secrets.AWS_SECRET_NAME }}
        run: |
          # Install boto3 (AWS SDK for Python)
          pip install boto3

          # Fetch the secret from AWS Secrets Manager
          import boto3
          import json
          import os

          client = boto3.client(
              'secretsmanager',
              aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
              aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
              region_name=os.environ['AWS_REGION']
          )

          response = client.get_secret_value(SecretId=os.environ['SECRET_NAME'])
          secret = json.loads(response['SecretString'])

          # Save email credentials as environment variables
          print(f"::set-output name=EMAIL_USER::{secret['EMAIL_USER']}")
          print(f"::set-output name=EMAIL_PASSWORD::{secret['EMAIL_PASSWORD']}")

      # Step 3: Run your pipeline (replace this with your actual pipeline steps)
      - name: Run pipeline
        run: |
          echo "Running your pipeline..."
          # Add your pipeline steps here (e.g., build, test, deploy)

      # Step 4: Send success email
      - name: Send success email
        if: success()
        env:
          EMAIL_USER: ${{ steps.fetch-secrets.outputs.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ steps.fetch-secrets.outputs.EMAIL_PASSWORD }}
        run: |
          echo "Pipeline succeeded! Sending email..."
          python -c "
          import smtplib
          from email.mime.text import MIMEText

          email_user = '${{ env.EMAIL_USER }}'
          email_password = '${{ env.EMAIL_PASSWORD }}'
          recipient = email_user  # Send to yourself, or replace with another email

          msg = MIMEText('Your pipeline succeeded!')
          msg['Subject'] = 'Pipeline Success'
          msg['From'] = email_user
          msg['To'] = recipient

          with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
              server.login(email_user, email_password)
              server.sendmail(email_user, recipient, msg.as_string())
          "

      # Step 5: Send failure email
      - name: Send failure email
        if: failure()
        env:
          EMAIL_USER: ${{ steps.fetch-secrets.outputs.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ steps.fetch-secrets.outputs.EMAIL_PASSWORD }}
        run: |
          echo "Pipeline failed! Sending email..."
          python -c "
          import smtplib
          from email.mime.text import MIMEText

          email_user = '${{ env.EMAIL_USER }}'
          email_password = '${{ env.EMAIL_PASSWORD }}'
          recipient = email_user  # Send to yourself, or replace with another email

          msg = MIMEText('Your pipeline failed!')
          msg['Subject'] = 'Pipeline Failure'
          msg['From'] = email_user
          msg['To'] = recipient

          with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
              server.login(email_user, email_password)
              server.sendmail(email_user, recipient, msg.as_string())
          "
