name: Fetch Secrets from Vault

on:
  push:
    branches:
      - main

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Retrieve Secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}  # Vault address stored in GitHub Secrets
          method: token  # You can change this to 'github' or 'approle' depending on your authentication method
          token: ${{ secrets.VAULT_TOKEN }}  # Vault token stored in GitHub Secrets
          secrets: |
            secret/github EMAIL_USERNAME | EMAIL_USERNAME
            secret/github EMAIL_PASSWORD | EMAIL_PASSWORD

      - name: Use Retrieved Secrets
        run: |
          echo "Email Username: $EMAIL_USERNAME"
          echo "Email Password: $EMAIL_PASSWORD"
        env:
          EMAIL_USERNAME: ${{ env.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ env.EMAIL_PASSWORD }}

